# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!
 
#pod 'Firebase'
pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'Firebase/Database'

target 'MelNote' do

end

target 'MelNoteTests' do

end

target 'MelNoteUITests' do

end

